package com.team7.propertypredict.helper;

import java.util.Arrays;
import java.util.List;

public class AmenityHelper {

	public static final List<String> markerPoints = Arrays.asList("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O");
	
	public static final List<String> nsLine = Arrays.asList("JURONG EAST MRT STATION (EW24/NS1)", "BUKIT BATOK MRT STATION (NS2)", "BUKIT GOMBAK MRT STATION (NS3)", "CHOA CHU KANG MRT STATION (NS4)",
			"YEW TEE MRT STATION (NS5)", "KRANJI MRT STATION (NS7)", "MARSILING MRT STATION (NS8)", "WOODLANDS MRT STATION (NS9)", "ADMIRALTY MRT STATION (NS10)", "SEMBAWANG MRT STATION (NS11)",
			"CANBERRA MRT STATION (NS12)", "YISHUN MRT STATION (NS13)", "KHATIB MRT STATION (NS14)", "YIO CHU KANG MRT STATION (NS15)", "ANG MO KIO MRT STATION (NS16)", "BISHAN MRT STATION (NS17)", 
			"BRADDEL MRT STATION (NS18)", "TOA PAYOH MRT STATION (NS19)", "NOVENA MRT STATION (NS20)", "NEWTON MRT STATION (NS21)", "ORCHARD MRT STATION (NS22)", "SOMERSET MRT STATION (NS23)",
			"DHOBY GAUT MRT STATION (NS24)", "CITY HALL MRT STATION (EW13/NS25)", "RAFFLES PLACE MRT STATION (EW14/NS26)", "MARINA BAY MRT STATION (NS27)", "MARINA SOUTH PIER MRT STATION (NS28)");
	
	public static final List<String> neLine = Arrays.asList("HARBOURFRONT MRT STATION (NE1/CC29)", "OUTRAM PARK MRT STATION (NE3)", "CHINATOWN MRT STATION (NE4)", "CLARKE QUAY MRT STATION (NE5)",
			"DHOBY GAUT MRT STATION (NE6)", "LITTLE INDIA MRT STATION (NE7)", "FARRER PARK MRT STATION (NE8)", "BOON KENG MRT STATION (NE9)", "POTONG PASIR MRT STATION (NE10)", "WOODLEIGH MRT STATION (NE11)",
			"SERANGOON MRT STATION (NE12)", "KOVAN MRT STATION (NE13)", "HOUGANG MRT STATION (NE14)", "BUANGKOK MRT STATION (NE15)", "SENGKANG MRT STATION (NE16)", "PUNGGOL MRT STATION (NE17)");
	
	public static final List<String> ewLine = Arrays.asList("EXPO MRT STATION (CG1)", "CHANGI AIRPORT MRT STATION (CG2)", "PASIR RIS MRT STATION (EW1)", "TAMPINES MRT STATION (EW2)", "SIMEI MRT STATION (EW3)",
			"TANAH MERAH MRT STATION (EW4)", "BEDOK MRT STATION (EW5)", "KEMBANGAN MRT STATION (EW6)", "EUNOS MRT STATION (EW7)", "PAYA LEBAR MRT STATION (EW8)", "ALJUNIED MRT STATION (EW9)",
			"KALLANG MRT STATION (EW10)", "LAVENDER MRT STATION (EW11)", "BUGIS MRT STATION (EW12)", "CITY HALL MRT STATION (EW13/NS25)", "RAFFLES PLACE MRT STATION (EW14/NS26)",
			"TANJONG PAGAR MRT STATION (EW15)", "OUTRAM PARK MRT STATION (EW16)", "TIONG BAHRU MRT STATION (EW17)", "REDHILL MRT STATION (EW18)", "QUEENSTOWN MRT STATION (EW19)", "COMMONWEALTH MRT STATION (EW20)",
			"BUONA VISTA MRT STATION (EW21)", "DOVER MRT STATION (EW22)", "CLEMENTI MRT STATION (EW23)", "JURONG EAST MRT STATION (EW24/NS1)", "CHINESE GARDEN MRT STATION (EW25)", "LAKESIDE MRT STATION (EW26)",
			"BOON LAY MRT STATION (EW27)", "PIONEER MRT STATION (EW28)", "JOO KOON MRT STATION (EW29)", "GUL CIRCLE MRT STATION (EW30)", "TUAS CRESCENT MRT STATION (EW31)", "TUAS WEST ROAD MRT STATION (EW32)",
			"TUAS LINK MRT STATION (EW33)");
	
	public static final List<String> ccLine = Arrays.asList("HARBOURFRONT MRT STATION (NE1/CC29)", "TELOK BELANGAH MRT STATION (CC28)", "LABRADOR PARK MRT STATION (CC27)", "PASIR PANJANG MRT STATION (CC26)",
			"HAW PAR VILLA MRT STATION (CC25)", "KENT RIDGE MRT STATION (CC24)", "ONE-NORTH MRT STATION (CC23)", "BUONA VISTA MRT STATION (CC22)", "HOLLAND VILLAGE MRT STATION (CC21)", "FARRER ROAD MRT STATION (CC20)",
			"BOTANIC GARDENS MRT STATION (CC19)", "CALDECOTT MRT STATION (CC17)", "MARYMOUNT MRT STATION (CC16)", "BISHAN MRT STATION (CC15)", "LORONG CHUAN MRT STATION (CC14)", "SERANGOON MRT STATION (CC13)",
			"BARTLEY MRT STATION (CC12)", "TAI SENG MRT STATION (CC11)", "MACPHERSON MRT STATION (CC10)", "PAYA LEBAR MRT STATION (CC9)", "DAKOTA MRT STATION (CC8)", "MOUNTBATTEN MRT STATION (CC7)",
			"STADIUM MRT STATION (CC6)", "NICOLL HIGHWAY MRT STATION (CC5)", "PROMENADE MRT STATION (CC4)", "ESPLANADE MRT STATION (CC3)", "BRAS BASAH MRT STATION (CC2)", "DHOBY GAUT MRT STATION (CC1)",
			"BAYFRONT MRT STATION (CE1)", "MARINA BAY MRT STATION (CE2)");
	
	public static final List<String> dtLine = Arrays.asList("BUKIT PANJANG MRT STATION (DT1)", "CASHEW MRT STATION (DT2)", "HILLVIEW MRT STATION (DT3)", "BEAUTY WORLD MRT STATION (DT5)", "KING ALBERT PARK MRT STATION (DT6)",
			"SIXTH AVENUE MRT STATION (DT7)", "TAN KAH KEE MRT STATION (DT8)", "BOTANIC GARDENS MRT STATION (DT9)", "STEVENS MRT STATION (DT10)", "NEWTON MRT STATION (DT11)", "LITTLE INDIA MRT STATION (DT12)", "ROCHOR MRT STATION (DT13)",
			"BUGIS MRT STATION (DT14)", "PROMENADE MRT STATION (DT15)", "BAYFRONT MRT STATION (DT16)", "DOWNTOWN MRT STATION (DT17)", "TELOK AYER MRT STATION (DT18)", "CHINATOWN MRT STATION (DT19)", "FORT CANNING MRT STATION (DT20)",
			"BENCOOLEN MRT STATION (DT21)", "JALAN BESAR MRT STATION (DT22)", "BENDEMEER MRT STATION (DT23)", "GEYLANG BAHRU MRT STATION (DT24)", "MATTAR MRT STATION (DT25)", "MACPHERSON MRT STATION (DT26)", "UBI MRT STATION (DT27)",
			"KAKI BUKIT MRT STATION (DT28)", "BEDOK NORTH MRT STATION (DT29)", "BEDOK RESERVOIR MRT STATION (DT30)", "TAMPINES WEST MRT STATION (DT31)", "TAMPINES MRT STATION (DT32)", "TAMPINES EAST MRT STATION (DT33)",
			"UPPER CHANGI MRT STATION (DT34)", "EXPO MRT STATION (DT35)");
}
