package com.team7.propertypredict.helper;

import java.util.Arrays;
import java.util.List;

public class AmenityHelper {

	public static final List<String> markerPoints = Arrays.asList("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O");
	
	public static final List<String> nsLine = Arrays.asList("JURONG EAST MRT STATION (EW24/NS1)", "BUKIT BATOK MRT STATION (NS2)", "BUKIT GOMBAK MRT STATION (NS3)", "CHOA CHU KANG MRT STATION (NS4)",
			"YEW TEE MRT STATION (NS5)", "KRANJI MRT STATION (NS7)", "MARSILING MRT STATION (NS8)", "WOODLANDS MRT STATION (NS9)", "ADMIRALTY MRT STATION (NS10)", "SEMBAWANG MRT STATION (NS11)",
			"CANBERRA MRT STATION (NS12)", "YISHUN MRT STATION (NS13)", "KHATIB MRT STATION (NS14)", "YIO CHU KANG MRT STATION (NS15)", "ANG MO KIO MRT STATION (NS16)", "BISHAN MRT STATION (NS17)", 
			"BRADDEL MRT STATION (NS18)", "TOA PAYOH MRT STATION (NS19)", "NOVENA MRT STATION (NS20)", "NEWTON MRT STATION (NS21)", "ORCHARD MRT STATION (NS22)", "SOMERSET MRT STATION (NS23)",
			"DHOBY GAUT MRT STATION (NS24)", "CITY HALL MRT STATION (EW13/NS25)", "RAFFLES PLACE MRT STATION (EW14/NS26)", "MARINA BAY MRT STATION (NS27)", "MARINA SOUTH PIER MRT STATION (NS28)");
	
	public static final List<String> neLine = Arrays.asList("HARBOURFRONT MRT STATION (NE1/CC29)", "OUTRAM PARK MRT STATION (NE3)", "CHINATOWN MRT STATION (NE4)", "CLARKE QUAY MRT STATION (NE5)",
			"DHOBY GAUT MRT STATION (NE6)", "LITTLE INDIA MRT STATION (NE7)", "FARRER PARK MRT STATION (NE8)", "BOON KENG MRT STATION (NE9)", "POTONG PASIR MRT STATION (NE10)", "WOODLEIGH MRT STATION (NE11)",
			"SERANGOON MRT STATION (NE12)", "KOVAN MRT STATION (NE13)", "HOUGANG MRT STATION (NE14)", "BUANGKOK MRT STATION (NE15)", "SENGKANG MRT STATION (NE16)", "PUNGGOL MRT STATION (NE17)");
}
